### ISSUE TITLE
Odoo Erasing POS orders when IoT is Enabled

### ISSUE THREAD

**Issue by kanys5** [akretion/pywebdriver#134] opened 2023-06-01 09:05 UTC
We have encountered a problem involving the use of Pywebdriver with five printers, which has resulted in fraudulent activity. When the IoT feature is enabled in Odoo, the system inadvertently deletes orders whenever a waiter prints a bill and rapidly refreshes the browser by pressing F5. 

As a consequence, Odoo loses the record of the printed order, allowing the waiter to potentially keep any cash payment associated with the order. This issue has been observed in both Odoo 14 ee&ce and Odoo 16 ee versions, persisting regardless of the version and when Pywebdriver is used in conjunction with IoT.

See reference video https://drive.google.com/file/d/1IwqfNhe3aXRYkqKTg7oH2-dJsSJxzD6L/view?usp=sharing

**Comment by legalsylvain** [comment] 2023-06-01 09:31
Hi. Interesting topic indeed. 
At the first glance, you describe a problem of Odoo Point of Sale. As far as I understand, the problem is not related to pywebdriver, and should occures also with "classic odoo IoT box".
For that reason, I think that this issue is not on the good repo. You should open an issue on odoo/odoo. (or use OPW, if you have EE contract).
Feel free to make a link to that issue, so we can follow the resolution of this problem.

CC : @OCA/pos-maintainers 

Closing in the meantime.

**Closed by legalsylvain** 2023-06-01 09:31 UTC
